import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useCompany } from "../context/CompanyContext";
import { queryKeys } from "../lib/queryKeys";
import { reportsApi } from "../api/reports";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FileText, Trash2, Plus } from "lucide-react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/context/ToastContext";

const typeLabels: Record<string, string> = {
  custom: "Custom",
  summary: "Summary",
  eod: "End of Day",
  import: "Import",
};

interface ReportsPanelProps {
  reports: Array<{
    id: string;
    type: string;
    title: string;
    generatedBy: string | null;
    generatedAt: Date | null;
    createdAt: Date;
  }>;
}

export function ReportsPanel({ reports }: ReportsPanelProps) {
  const { selectedCompanyId } = useCompany();
  const queryClient = useQueryClient();
  const { pushToast } = useToast();
  const [offset, setOffset] = useState(0);
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [newReport, setNewReport] = useState({
    title: "",
    type: "custom" as string,
    content: "",
  });
  const limit = 20;

  const { data, isLoading } = useQuery({
    queryKey: [...queryKeys.reports(selectedCompanyId!), { offset, limit }],
    queryFn: () =>
      reportsApi.list(selectedCompanyId!, { offset: String(offset), limit: String(limit) }),
    enabled: !!selectedCompanyId,
  });

  const createMutation = useMutation({
    mutationFn: (body: { type: "summary" | "import" | "custom" | "eod"; title: string; contentJson?: Record<string, unknown> }) =>
      reportsApi.create(selectedCompanyId!, body),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.reports(selectedCompanyId!) });
      setShowCreateDialog(false);
      setNewReport({ title: "", type: "custom", content: "" });
      pushToast({ title: "Report created successfully" });
    },
    onError: (error) => {
      pushToast({ title: `Failed to create report: ${error.message}` });
    },
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => reportsApi.delete(selectedCompanyId!, id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.reports(selectedCompanyId!) });
      pushToast({ title: "Report deleted" });
    },
  });

  const displayReports = data?.reports ?? reports;

  const handleCreate = () => {
    if (!newReport.title.trim()) {
      pushToast({ title: "Title is required" });
      return;
    }
    const reportType = newReport.type as "summary" | "import" | "custom" | "eod";
    createMutation.mutate({
      type: reportType,
      title: newReport.title,
      contentJson: newReport.content ? { content: newReport.content } : undefined,
    });
  };

  return (
    <Card>
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg font-medium">Reports</CardTitle>
          <Button size="sm" onClick={() => setShowCreateDialog(true)}>
            <Plus className="h-4 w-4 mr-1" />
            Generate Report
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        {isLoading ? (
          <p className="text-sm text-muted-foreground">Loading reports...</p>
        ) : displayReports.length > 0 ? (
          <div className="space-y-4">
            <div className="rounded-md border">
              <div className="grid grid-cols-5 gap-4 p-3 text-sm font-medium text-muted-foreground border-b bg-muted/50">
                <div>Type</div>
                <div>Title</div>
                <div>Generated By</div>
                <div>Date</div>
                <div className="w-[50px]"></div>
              </div>
              <div className="divide-y">
                {displayReports.map((report) => (
                  <div key={report.id} className="grid grid-cols-5 gap-4 p-3 items-center">
                    <div>
                      <Badge variant="outline">{typeLabels[report.type] ?? report.type}</Badge>
                    </div>
                    <div className="font-medium">{report.title}</div>
                    <div className="text-sm text-muted-foreground">
                      {report.generatedBy}
                    </div>
                    <div className="text-sm text-muted-foreground">
                      {report.generatedAt
                        ? new Date(report.generatedAt).toLocaleDateString()
                        : new Date(report.createdAt).toLocaleDateString()}
                    </div>
                    <div>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-8 w-8 p-0"
                        onClick={() => deleteMutation.mutate(report.id)}
                      >
                        <Trash2 className="h-4 w-4 text-red-500" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            {data && data.total > limit && (
              <div className="flex items-center justify-between">
                <Button
                  variant="outline"
                  size="sm"
                  disabled={offset === 0}
                  onClick={() => setOffset((o) => Math.max(0, o - limit))}
                >
                  Previous
                </Button>
                <span className="text-sm text-muted-foreground">
                  Showing {offset + 1}–{Math.min(offset + limit, data.total)} of {data.total}
                </span>
                <Button
                  variant="outline"
                  size="sm"
                  disabled={offset + limit >= data.total}
                  onClick={() => setOffset((o) => o + limit)}
                >
                  Next
                </Button>
              </div>
            )}
          </div>
        ) : (
          <div className="flex flex-col items-center gap-2 py-8">
            <FileText className="h-8 w-8 text-muted-foreground" />
            <p className="text-sm text-muted-foreground">No reports generated yet.</p>
          </div>
        )}
      </CardContent>

      {/* Create Report Dialog */}
      <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Create New Report</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="title">Title</Label>
              <Input
                id="title"
                placeholder="Enter report title"
                value={newReport.title}
                onChange={(e) => setNewReport({ ...newReport, title: e.target.value })}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="type">Type</Label>
              <Select
                value={newReport.type}
                onValueChange={(value) => setNewReport({ ...newReport, type: value })}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select report type" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="custom">Custom</SelectItem>
                  <SelectItem value="eod">End of Day</SelectItem>
                  <SelectItem value="import">Import Summary</SelectItem>
                  <SelectItem value="summary">Summary</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="content">Content (optional)</Label>
              <Input
                id="content"
                placeholder="Enter report content"
                value={newReport.content}
                onChange={(e) => setNewReport({ ...newReport, content: e.target.value })}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreateDialog(false)}>
              Cancel
            </Button>
            <Button onClick={handleCreate} disabled={createMutation.isPending}>
              {createMutation.isPending ? "Creating..." : "Create Report"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </Card>
  );
}
